---
repository: sunderb/lhd-build-2020-hackathon-website-template
include: ["index.html", "_events",]

# Homepage settings
splash_title: 'Hack the Solar System'
splash_subtitle: 'A stellar hackathon!'
homepage_banner_image: photos/blurred-starry-sky.jpg
display_ad: true



footer-description: "Hack the Solar System is a student-run group that hosts hackathons focusing on astronomy and data science."


# Links for the navbar
navs:
  -
    name: Home
    link: "/#top"
  -
    name: Events
    link: "/#future-events"
  -
    name: Sponsor us
    link: "/assets/pdf/sponsordeck.pdf"


# Social media links included on the splash page
socials:
  #-
  ##  icon: "facebook-white.svg"
  #  name: Facebook
  #  url: "https://facebook.com/royalhackaway"
  -
    icon: "twitter.svg"
    name: Twitter
    url: "https://twitter.com/sunderb_"
  -
    icon: "github-mark.png"
    name: GitHub
    url: "https://github.com/SunderB"

email: hello@hackthesolarsystem.example.com


collections:
  events:
    output: true
    permalink: /:slug


sass:
  style: compressed
  sass_dir: _sass
